"""RealSO101Robot interface to communicate with physical SO-101 arm via Feetech servos."""

import json
from pathlib import Path

import numpy as np

try:
    from lerobot.motors.feetech import FeetechMotorsBus
    from lerobot.motors.motors_bus import Motor, MotorCalibration, MotorNormMode

    LEROBOT_AVAILABLE = True
except ImportError:
    LEROBOT_AVAILABLE = False

JOINT_NAMES = [
    "shoulder_pan",
    "shoulder_lift",
    "elbow_flex",
    "wrist_flex",
    "wrist_roll",
    "gripper",
]

# Standard calibration file location generated by `lerobot-calibrate`
DEFAULT_CALIB_PATH = (
    Path.home() / ".cache/huggingface/lerobot/calibration/robots/so101_follower/follower_droid.json"
)


class RealSO101Robot:
    """Wrapper class for physical SO-101 robot arm using Feetech STS3215 servos."""

    def __init__(
        self,
        port: str = "/dev/tty.usbmodem1201",
        baudrate: int = 1_000_000,
        calibration_path: str | Path | None = None,
    ):
        """Initialize connection to physical Feetech motors bus with LeRobot calibration.

        Args:
            port: Serial port device path (e.g., /dev/tty.usbmodem1201 or /dev/ttyUSB0).
            baudrate: Motors bus communication baudrate (default: 1,000,000).
            calibration_path: Path to `follower_droid.json` calibration file.
        """
        self.port = port
        self.baudrate = baudrate
        self.connected = False

        if calibration_path is None:
            calibration_path = DEFAULT_CALIB_PATH
        self.calibration_path = Path(calibration_path)

        if not LEROBOT_AVAILABLE:
            print("Notice: 'lerobot' package is not installed or available.")
            self.bus = None
            return

        # Define Motor objects with MotorNormMode.DEGREES so LeRobot normalizes to degrees
        self.motors = {
            "shoulder_pan": Motor(id=1, model="sts3215", norm_mode=MotorNormMode.DEGREES),
            "shoulder_lift": Motor(id=2, model="sts3215", norm_mode=MotorNormMode.DEGREES),
            "elbow_flex": Motor(id=3, model="sts3215", norm_mode=MotorNormMode.DEGREES),
            "wrist_flex": Motor(id=4, model="sts3215", norm_mode=MotorNormMode.DEGREES),
            "wrist_roll": Motor(id=5, model="sts3215", norm_mode=MotorNormMode.DEGREES),
            "gripper": Motor(id=6, model="sts3215", norm_mode=MotorNormMode.DEGREES),
        }

        # Load calibration if available
        self.calibration = None
        if self.calibration_path.exists():
            try:
                calib_data = json.loads(self.calibration_path.read_text())
                self.calibration = {
                    name: MotorCalibration(**cfg) for name, cfg in calib_data.items()
                }
                print(f"Loaded LeRobot calibration profile from {self.calibration_path}")
            except Exception as e:
                print(f"Warning: Could not load calibration file {self.calibration_path}: {e}")
        else:
            print(
                f"Notice: Calibration file {self.calibration_path.name} not found. "
                "Running without calibration."
            )

        try:
            self.bus = FeetechMotorsBus(
                port=self.port,
                motors=self.motors,
                calibration=self.calibration,
            )
            self.bus.connect()
            self.connected = True
            print(f"Successfully connected to real SO-101 arm on port {self.port}.")
        except Exception as e:
            print(f"Warning: Could not connect to physical robot on port {self.port}: {e}")
            print("Running in mock hardware mode.")
            self.bus = None
            self.connected = False

        self._mock_qpos = np.zeros(6, dtype=np.float32)

    def set_joint_positions(self, qpos: np.ndarray) -> None:
        """Command target joint positions (in radians) to physical motors using calibration.

        Args:
            qpos: Target joint angles in radians for 6 joints.
        """
        qpos = np.asarray(qpos, dtype=np.float32)
        self._mock_qpos = qpos.copy()

        if not self.connected or self.bus is None:
            return

        # If calibration is loaded, convert radians to degrees for LeRobot normalized write
        if self.calibration is not None:
            joint_degrees = {}
            for i, joint_name in enumerate(JOINT_NAMES):
                deg = float(np.degrees(qpos[i]))
                joint_degrees[joint_name] = deg

            try:
                # Use sync_write to update all joint Goal_Positions cleanly
                self.bus.sync_write("Goal_Position", joint_degrees, normalize=True)
            except Exception as e:
                print(f"Error writing joint positions to bus: {e}")
        else:
            # Fallback raw position calculation if no calibration profile
            TICKS_PER_RAD = 4096.0 / (2.0 * np.pi)
            CENTER_TICK = 2048
            joint_dict = {}
            for i, joint_name in enumerate(JOINT_NAMES):
                tick = int(round(CENTER_TICK + qpos[i] * TICKS_PER_RAD))
                joint_dict[joint_name] = tick

            try:
                self.bus.sync_write("Goal_Position", joint_dict, normalize=False)
            except Exception as e:
                print(f"Error writing raw joint positions: {e}")

    def get_joint_positions(self) -> np.ndarray:
        """Read current joint positions from physical motor encoders in radians.

        Returns:
            A numpy array of 6 joint positions in radians.
        """
        if not self.connected or self.bus is None:
            return self._mock_qpos.copy()

        try:
            if self.calibration is not None:
                deg_dict = self.bus.sync_read("Present_Position", normalize=True)
                qpos = np.zeros(6, dtype=np.float32)
                for i, joint_name in enumerate(JOINT_NAMES):
                    if joint_name in deg_dict:
                        qpos[i] = np.radians(deg_dict[joint_name])
                    else:
                        qpos[i] = self._mock_qpos[i]
                return qpos
            else:
                TICKS_PER_RAD = 4096.0 / (2.0 * np.pi)
                CENTER_TICK = 2048
                tick_dict = self.bus.sync_read("Present_Position", normalize=False)
                qpos = np.zeros(6, dtype=np.float32)
                for i, joint_name in enumerate(JOINT_NAMES):
                    if joint_name in tick_dict:
                        qpos[i] = (tick_dict[joint_name] - CENTER_TICK) / TICKS_PER_RAD
                    else:
                        qpos[i] = self._mock_qpos[i]
                return qpos
        except Exception as e:
            print(f"Error reading present positions from bus: {e}")
            return self._mock_qpos.copy()

    def disconnect(self) -> None:
        """Disconnect and release the serial bus."""
        if self.connected and self.bus is not None:
            try:
                self.bus.disconnect()
                self.connected = False
                print("Disconnected from physical SO-101 robot arm.")
            except Exception as e:
                print(f"Error disconnecting: {e}")
